### Two Dimensional NumPy

In [2]:
import numpy as np
a=[[11,12,13],[21,22,23],[31,32,33]]
A=np.array(a)
print(A)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [3]:
print(A.ndim)

2


In [4]:
print(A.shape)

(3, 3)


In [5]:
print(A.size)

9


In [6]:
print(A[0,0:2])

[11 12]


In [8]:
a=[[1,0],[0,1]]
b=[[2,1],[1,2]]
p=np.array(a)
o=np.array(b)
print(p+o)

[[3 1]
 [1 3]]


In [10]:
print(2*o)

[[4 2]
 [2 4]]


In [11]:
print(p*o)

[[2 0]
 [0 2]]


In [12]:
print(np.multiply(p,o))

[[2 0]
 [0 2]]


In [13]:
print(np.dot(p,o))

[[2 1]
 [1 2]]


### Exercise 

In [21]:
a=[[11,12,13],[21,22,23],[31,32,33]]
matrix1=np.array(a)
print(matrix1)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [22]:
# Access the element on the second row and third column
print(matrix1[1][2])

23


In [23]:
# Access the element on the first row and first and second columns
print(matrix1[0][0:2])

[11 12]


In [26]:
# Access the element on the first and second rows and third column
print(matrix1[0:2,2])

[13 23]
